### ISSUE TITLE
TypeError when invoking Chatbot Lambda (alt_kendra_idxs.includes is not a function")

### ISSUE THREAD

**Issue by feelec1** [aws-solutions/qnabot-on-aws#568]
**Describe the bug**

When attempt to test the Q&A chatbot by asking a populated question I see a TypeError in the Lambda with the message alt_kendra_idxs.includes is not a function"

{     "errorType": "TypeError",     "errorMessage": "alt_kendra_idxs.includes is not a function",     
      "stack": [         
                    "TypeError: alt_kendra_idxs.includes is not a function",         
                    "    at run_query_kendra (/opt/lib/query.js:56:25)",         
                    "    at run_query (/opt/lib/query.js:23:25)",         
                    "    at async get_hit (/opt/lib/query.js:256:20)",         
                    "    at async processFulfillmentEvent (/opt/lib/query.js:629:27)",         
                    "    at async module.exports (/opt/lib/query.js:777:17)",         
                    "    at async Array.query (/var/task/lib/middleware/3_query.js:139:21)",         
                    "    at async router._walk (/var/task/lib/router/index.js:34:24)",         
                    "    at async router._walk (/var/task/lib/router/index.js:35:20)",         
                    "    at async router._walk (/var/task/lib/router/index.js:35:20)",         
                    "    at async router.start (/var/task/lib/router/index.js:14:21)" 
]}

This is evident in the QnA-ChatBot-FulfillmentLambda Lambda function.

**To Reproduce**

1. Create new stack from here: https://solutions-reference.s3.amazonaws.com/qnabot-on-aws/v5.3.0/qnabot-on-aws-main.template
2. Deploy stack
3. Once complete, create questions, and run query through client (should be successful)

**Priority**
P4

**Screenshots/Video**
N/A

**Desktop**
OS: [iOS]
Browser [chrome]
Region [eu-west-2]

**Comment by feelec1** [comment]
Thanks @ihmaws I'm changing a parameter and going to test again. It could be down to a misconfiguration.

**Comment by feelec1** [comment]
Hi @ihmaws it was a misconfiguration. I will remove this, thanks for coming back to me.
